name: PKGBUILD CI
on: 
  push:
  workflow_dispatch:
jobs:
  build_with_gcc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.7
      with:
          pkgdir: "gcc-actiondir"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
          aurDeps: 1
    - name: Release
      uses: ncipollo/release-action@v1.8.6
      with:
          allowUpdates: true
          tag: "5.16.13-1-gcc"
          commit: master
          artifacts: "./*/*.zst"
          token: ${{ secrets.GH_TOKEN }}
  build_with_lto:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.6
      with:
          pkgdir: "lto-actiondir"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
          aurDeps: 1
    - name: Release
      uses: ncipollo/release-action@v1.9.0
      with:
          allowUpdates: true
          tag: "5.16.13-1-lto"
          commit: master
          artifacts: "./*/*.zst"
          token: ${{ secrets.GH_TOKEN }}
